/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package race_time_recording.view;

import java.awt.Font;
import javax.swing.DefaultListModel;
import race_time_recording.controller.InitialSettingsController;
import race_time_recording.controller.MainMenuController;
import race_time_recording.model.StarterTableModel;

/**
 *
 * @author LiTeM
 */
public class MainMenuFrame extends javax.swing.JFrame {

    private StarterTableModel starterTableModel;
    private Font timeFont, roundFont;
    private final MainMenuController controller;

    /**
     * Creates new form MainMenuFrame
     * @param controller
     */
    public MainMenuFrame(MainMenuController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        geschicklichkeitButton = new javax.swing.JButton();
        ackerlaufButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kartslalomButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Race Time Recording");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(900, 350));
        setMinimumSize(new java.awt.Dimension(900, 350));
        setPreferredSize(new java.awt.Dimension(940, 350));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        geschicklichkeitButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        geschicklichkeitButton.setText("Geschicklichkeit");
        geschicklichkeitButton.setToolTipText("");
        geschicklichkeitButton.setActionCommand("<html><center>Neues</center><br><center>Rennen</center></html>");
        geschicklichkeitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geschicklichkeitButtonActionPerformed(evt);
            }
        });

        ackerlaufButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ackerlaufButton.setText("Ackerlauf");
        ackerlaufButton.setToolTipText("");
        ackerlaufButton.setActionCommand("<html><center>Neues</center><br><center>Rennen</center></html>");
        ackerlaufButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ackerlaufButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcher Typ soll gestartet werden?");

        kartslalomButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        kartslalomButton.setText("Kartslalom");
        kartslalomButton.setToolTipText("");
        kartslalomButton.setActionCommand("<html><center>Neues</center><br><center>Rennen</center></html>");
        kartslalomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartslalomButtonActionPerformed(evt);
            }
        });

        loadButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loadButton.setText("Bestehendes Rennen laden");
        loadButton.setToolTipText("");
        loadButton.setActionCommand("<html><center>Neues</center><br><center>Rennen</center></html>");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(loadButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ackerlaufButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kartslalomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(geschicklichkeitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ackerlaufButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kartslalomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geschicklichkeitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geschicklichkeitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geschicklichkeitButtonActionPerformed
        controller.changeFrame("geschicklichkeit");
    }//GEN-LAST:event_geschicklichkeitButtonActionPerformed

    private void ackerlaufButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ackerlaufButtonActionPerformed
        controller.changeFrame("acker");
    }//GEN-LAST:event_ackerlaufButtonActionPerformed

    private void kartslalomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartslalomButtonActionPerformed
        controller.changeFrame("kart");
    }//GEN-LAST:event_kartslalomButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadButtonActionPerformed


    public void setStarterList(String list) {
        DefaultListModel demoList = new DefaultListModel();
        demoList.addElement(list);
        //starterList2.setModel(demoList);
    }

    public void initFrame() {
        initComponents();
    }

    public void setTimeFont(Font digitFont) {
        this.timeFont = digitFont;
    }

    public Font getTimeFont() {
        return timeFont;
    }

    public void setRoundFont(Font roundFont) {
        this.roundFont = roundFont;
    }

    public Font getRoundFont() {
        return roundFont;
    }

    public void setStarterTableModel(StarterTableModel starterTableModel) {
        this.starterTableModel = starterTableModel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ackerlaufButton;
    private javax.swing.JButton geschicklichkeitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kartslalomButton;
    private javax.swing.JButton loadButton;
    // End of variables declaration//GEN-END:variables
}
